name: Pull_Push_Schedule

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟触发一次

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.26.4 ccxt==4.2.15 pandas==2.2.0 pandas-ta==0.3.14b pytz==2024.1
        
    - name: Run script
      run: python main.py

    - name: Organize and push CSV files
      run: |
        DATE=$(date +'%Y-%m-%d')  # 创建日期文件夹并移动文件
        mkdir -p $DATE
        mv screened_symbols_*.csv $DATE/
        git config --global user.name 'github-actions[bot]'  # 提交并推送文件
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull origin main  # 拉取远程更改
        git add $DATE/screened_symbols_*.csv
        git commit -m "Add output CSV file for $DATE"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
